# This is a basic workflow to help you get started with Actions

name: ArtifactParser

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 2.0.x ]
  pull_request:
    branches: [ 2.0.x ]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Build with Maven
        run: |
          mvn clean install
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target-artifact
          path: |
            target
            **/target
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-result-junit
          path: target/surefire-reports/
