# This is a basic workflow to help you get started with Actions

name: ThundraCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ 2.0.x ]
  pull_request:
    branches: [ 2.0.x ]
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Thundra Maven Test Instrumentation
        uses: thundra-io/thundra-maven-test-action@v1
        env:
           THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.io/v1
        with:
          apikey: 21d92227-07db-44d1-a16c-34476c08e6e5
          project_id: d1112683-31ec-4105-85eb-3c0ab906984f
          command: mvn clean install
